### ISSUE TITLE
Missing BMH fields cause panic

### ISSUE THREAD

**Issue by drewwalters96** [att-comdev/sip#6]
SIP requires some [BMH fields](https://github.com/att-comdev/sip/blob/master/pkg/vbmh/machines.go#L407-L408), including `Spec.NetworkData.Namespace` and `Spec.NetworkData.Name`. When BMHs are pushed to K8s without these fields, SIP panics.

**Comment by alexander-hughes** [comment]
Still working on this, had some difficulty last week reproducing the error.  Several possible attempts to resolve have failed, including removing the check from pkg/vbmh/machines.go Extrapolate function:

```
		//// Skip if I alread extrapolated tehh data for this machine
		//if len(machine.Data.IpOnInterface) > 0 {
		//	continue
		//}
```

The particular error we're seeing is when a vbmh is missing the networkData.Name or networkData.Namespace fields.  To reproduce this error:

1. Stand up development environment as described in https://github.com/att-comdev/sip/blob/master/README.md
2. Comment out all of the networkData fields in config/samples/bmh/bmh.yaml
3. kustomize build config/samples | kubectl apply -f -
4. This will put the sip controller into a crashloop.  With log entries like the following (from the manager container):

```
2020-12-07T14:03:38.722Z        INFO    controllers.SIPCluster.machines Found machines for scheduling   {"SIPCluster": "sipcluster-system/sipcluster-test1", "count": 5}
Schedule.Extrapolate.getIp machine.Data.IpOnInterface[oam-ipv4]:32.68.51.140
Schedule.Extrapolate  machine.Data.IpOnInterface len:0 machine:Machine {
        Bmh:rdm9r007o001
        ScheduleStatus:Selected
        VmRole:master
E1207 14:03:38.824246       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 212 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1540960, 0x24568b0)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1540960, 0x24568b0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
sipcluster/pkg/vbmh.(*MachineList).Extrapolate(0xc0004145c0, 0x1414316, 0xa, 0xc0000d8660, 0x18, 0xc000321c00, 0x10, 0x0, 0x0, 0xc00028a780, ...)
        /workspace/pkg/vbmh/machines.go:396 +0x29a
sipcluster/pkg/controllers.(*SIPClusterReconciler).gatherVBMH(0xc0004314a0, 0x1414316, 0xa, 0xc0000d8660, 0x18, 0xc000321c00, 0x10, 0x0, 0x0, 0xc00028a780, ...)
        /workspace/pkg/controllers/sipcluster_controller.go:183 +0x380
sipcluster/pkg/controllers.(*SIPClusterReconciler).Reconcile(0xc0004314a0, 0xc00028a780, 0x11, 0xc000321c00, 0x10, 0xc000306280, 0xc00020e2d8, 0x1912200, 0xc00020e2d0)
        /workspace/pkg/controllers/sipcluster_controller.go:68 +0x2b9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004ecf30, 0x1597a60, 0xc000226540, 0x43e600)
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244 +0x27d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004ecf30, 0x0)
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0004ecf30)
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000306240)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000306240, 0x1903cc0, 0xc000367ec0, 0x1, 0xc0004e83c0)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000306240, 0x3b9aca00, 0x0, 0x1, 0xc0004e83c0)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc000306240, 0x3b9aca00, 0xc0004e83c0)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.19.0/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:179 +0x44d
}
```

**Comment by alexander-hughes** [comment]
Work in progress, tracked in https://github.com/att-comdev/sip/pull/22

**Comment by alexander-hughes** [comment]
PR #22 abandoned, but https://github.com/att-comdev/sip/pull/23 was merged resolving this issue.
